[build]
  command = "cd react-app && yarn install && yarn build && cd ../mazegames && yarn install && yarn build"
  publish = "react-app/dist" # Path to the React app's build output

[[redirects]]
  from = "/mazegames/*"
  to = "/mazegames/index.html"
  status = 200
