[build]
  command = "yarn install && yarn build"
  publish = "react-app/dist"

[[redirects]]
  from = "/mazegames/*"
  to = "/mazegames/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/mazegames/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"